"""primeira migration

Revision ID: 3c60852bfcad
Revises: 
Create Date: 2026-01-28 19:03:57.887376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c60852bfcad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nm_usuario', sa.String(length=50), nullable=False),
    sa.Column('nm_username', sa.String(length=16), nullable=False),
    sa.Column('dsc_email', sa.String(length=30), nullable=False),
    sa.Column('pw_senha', sa.String(length=16), nullable=False),
    sa.Column('st_partida', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('dsc_email'),
    sa.UniqueConstraint('nm_usuario')
    )
    op.create_table('tb_enigma',
    sa.Column('id_enigma', sa.Integer(), nullable=False),
    sa.Column('txt_titulo', sa.String(length=50), nullable=False),
    sa.Column('txt_descricao', sa.String(length=100), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['tb_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_enigma')
    )
    op.create_table('tb_lista_contato',
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('id_contato', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contato'], ['tb_usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_proprietario'], ['tb_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_proprietario', 'id_contato')
    )
    op.create_table('tb_partida',
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.Column('dt_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_fim', sa.DateTime(), nullable=True),
    sa.Column('id_enigma', sa.Integer(), nullable=False),
    sa.Column('id_anfitriao', sa.Integer(), nullable=False),
    sa.Column('id_convidado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_anfitriao'], ['tb_usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_convidado'], ['tb_usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_enigma'], ['tb_enigma.id_enigma'], ),
    sa.PrimaryKeyConstraint('id_partida')
    )
    op.create_table('tb_mensagem',
    sa.Column('id_mensagem', sa.Integer(), nullable=False),
    sa.Column('dt_mensagem', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('txt_mensagem', sa.String(length=100), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_partida', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_partida'], ['tb_partida.id_partida'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_mensagem')
    op.drop_table('tb_partida')
    op.drop_table('tb_lista_contato')
    op.drop_table('tb_enigma')
    op.drop_table('tb_usuario')
    # ### end Alembic commands ###
